### ISSUE TITLE
Review release notes

### ISSUE THREAD

**Issue by jschlyter** [kirei/hass-chargeamps#12]
It would be most useful if @fredrike review the release notes for next release, as most new stuff originate from him.

**Comment by fredrike** [comment]
It looks good to me. Just add this.

* Fix deprecation warning of SwitchDevice

**Comment by jschlyter** [comment]
Found one important nit, please check 5bceb3e9215b1fc02c527b339278861101b60a38

**Comment by fredrike** [comment]
> Found one important nit, please check [5bceb3e](https://github.com/kirei/hass-chargeamps/commit/5bceb3e9215b1fc02c527b339278861101b60a38)

Nice catch!
