### ISSUE TITLE
Feature Request - add set current limit as a sensor or attribute

### ISSUE THREAD

**Issue by tubalainen** [kirei/hass-chargeamps#16]
Hi!

I use this fantastic component to throttle down the amps of the charger when my dryer is running. It works like a champ!
Would it be possible to as a separate sensor or as a sensor attribute add the current active "amps"?

Thanks

**Comment by jschlyter** [comment]
That should be available already as `lx_current` from the power sensors (which charging).

**Comment by tubalainen** [comment]
> That should be available already as `lx_current` from the power sensors (while charging).

Yes, that one I know. I´d like to know the setting prior to the charging starts if possible.

**Comment by jschlyter** [comment]
Before the charging starts, the current through the box is zero. Perhaps I'm missing something?

**Comment by tubalainen** [comment]
> Before the charging starts, the current through the box is zero. Perhaps I'm missing something?

Correct - the box does not draw any current when there isnt anything connected. But the parameter/attribute `set_max_current` - what is the current setting?

Equal to the information that I can see and read on my.charge.space (see picture).

På Svenska - jag önskar att kunna läsa av aktuell strömbegränsning innan laddningen påbörjas. Vad är `max_current` satt till?
![image](https://user-images.githubusercontent.com/26795429/98955216-ee1b6d00-24fe-11eb-8f54-619ce3a5ffc7.png)

**Comment by jschlyter** [comment]
Check the `max_current` attribute on the switch

**Comment by tubalainen** [comment]
*DOH*
Thanks! Searched for that among the sensors. My bad.
