### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by Schelin78** [kirei/hass-chargeamps#17]
Hi,
I´m getting this:

Invalid config
The following integrations and platforms could not be set up:

chargeamps
Please check your config and logs.

------------------------
Logger: homeassistant.setup
Source: custom_components/chargeamps/__init__.py:154
First occurred: 2:28:19 PM (1 occurrences)
Last logged: 2:28:19 PM

Error during setup of component chargeamps
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/chargeamps/__init__.py", line 115, in async_setup
    handler = ChargeampsHandler(hass, client, charge_point_ids, readonly, scan_interval)
  File "/config/custom_components/chargeamps/__init__.py", line 154, in __init__
    self.default_charge_point_id = charge_point_ids[0]
IndexError: list index out of range

**Comment by jschlyter** [comment]
How does your configuration look like? (replace any secrets with XXX!)

**Comment by Schelin78** [comment]
Hi, it looks like this:


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
  - platform: growatt
    username: XXX
    password: XXX
  - platform: template

chargeamps:
  username: XXX
  password: XXX
  api_key: XXX

**Comment by jschlyter** [comment]
It looks like you have no chargepoints connected to your account. Does it work from the Charge Amps web ui?

**Comment by Schelin78** [comment]
Might be that tried it on https://eapis.charge.space/swagger/index.html#/ tried Post "/api/v3/auth/login" and get ->
401 | Error: Unauthorized
API key is not valid!

**Comment by jschlyter** [comment]
Did you solve the issue?

**Comment by Schelin78** [comment]
Yes they sent me wrong api key all the time

Den mån 5 apr. 2021 22:34Jakob Schlyter ***@***.***> skrev:
