### ISSUE TITLE
Problem loading Chargeamps in Home Assistans OS 5.12

### ISSUE THREAD

**Issue by JorSjo** [kirei/hass-chargeamps#18]
After upgrading Core to Home Assistant OS 5.12 ChargeAmp is no longer loading with the following error.

```
Unable to install package chargeamps==1.4.0: ERROR: Package 'dataclasses' requires a different Python: 3.8.7 not in '>=3.6, <3.7' WARNING: You are using pip version 20.2.4
```
I will restore backup on my HomeAssistant and downgrade to 5.11 for now so posting Issue for your notice.

**Comment by jschlyter** [comment]
Fixed in version 1.4.2 (just released).
