### ISSUE TITLE
Consumption sensor not working with the new energy monitoring in HA

### ISSUE THREAD

**Issue by DanielOrneling** [kirei/hass-chargeamps#20]
Just tried to add the total consumption sensor to see how much charging the cars costs. It seems the integration itself needs to add the feature of energy monitoring.

Find out more here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by jschlyter** [comment]
I've added some basic, not yet released, support for this. If you want to help, please install manually and test.

**Comment by DanielOrneling** [comment]
I'd love to help. Can I find the newest version in the repo? Plus i don't remember how to install without hacs.

**Comment by jschlyter** [comment]
I've just published a new version that should resolve this, please test!

**Comment by DanielOrneling** [comment]
Works perfectly, thanks for a great integration!
