### ISSUE TITLE
Unexpected state class in in HA

### ISSUE THREAD

**Issue by DanielOrneling** [kirei/hass-chargeamps#21]
I just saw that with HA 2021.9.x the energy function isn´t working anymore, to fins out how much money is being spent.

Looking at the energy configuration page in HA (https://yourHAinstance:8123/config/energy) I get an error saying like below:'

Unexpected state class
The following entities do not have the expected state class 'total_increasing'
sensor.garaget_serialnumber_total_energy (measurement)

Anything I can add beisdes the above that is helpful to look at the issue?

**Comment by jschlyter** [comment]
xref: https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

**Comment by DanielOrneling** [comment]
Is there something I´m missing that I should setup from my end, or is that something that´s new to be implemented from your end?
I know there were some changes needed that you took care of when HA launched with the energy monitoring solution. I think that was 2021.8.0 where they launched that part.

**Comment by jschlyter** [comment]
It seems they've change the state classes, but failed to maintain backwards compatibility. I'll see if it is an easy fix.

**Comment by jschlyter** [comment]
Please try new release 1.5.1

**Comment by DanielOrneling** [comment]
It´s working again now with 1.5.1. Thanks for your quick response yet again. Much appreciated :)
