### ISSUE TITLE
core-2021.12.1

### ISSUE THREAD

**Issue by klotan** [kirei/hass-chargeamps#24]
![chargeamps](https://user-images.githubusercontent.com/61826413/145786875-3ad8cc74-21c2-475a-b0bf-ca86d7178f9d.PNG)

I get these warnings after install of the newest core

**Comment by klotan** [comment]
Något nytt?

**Comment by jschlyter** [comment]
We should move to `extra_state_attributes`, will try to fix before next release.

**Comment by jschlyter** [comment]
Fixed in https://github.com/kirei/hass-chargeamps/releases/tag/v1.6.0
