### ISSUE TITLE
Check Home Assistant configuration for 2022.2.2 gives an error

### ISSUE THREAD

**Issue by a94marbo** [kirei/hass-chargeamps#25]
The Check Home Assistant configuration gives the following error;
    - Component error: chargeamps - Exception importing custom_components.chargeamps
Does it still work? Anyone tried to upgrade to 2022.2.x?

**Comment by jschlyter** [comment]
I just tried and get no error in 2022.2.2, anything else the the error above?

**Comment by a94marbo** [comment]
Nope, I have checked all logs etc but no more info..
I can try an upgrade and see what happens

**Comment by a94marbo** [comment]
Seems to work after upgrade, no errors,
