### ISSUE TITLE
Recurring error

### ISSUE THREAD

**Issue by Bryggan** [kirei/hass-chargeamps#26]
Hi,

For a few months now, the integration has sometimes stopped working when restarting Home Assistant. It usually works again when I upgrade to a new version of Home Assistant, but not by a regular reboot. These are the error logs:

_Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/config/custom_components/chargeamps/__init__.py", line 113, in async_setup
    for cp in await client.get_chargepoints():
  File "/usr/local/lib/python3.9/site-packages/chargeamps/external.py", line 82, in get_chargepoints
    response = await self._get(request_uri)
  File "/usr/local/lib/python3.9/site-packages/chargeamps/external.py", line 68, in _get
    return await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected_

**Comment by elden1337** [comment]
+1

**Comment by elden1337** [comment]
@Bryggan, I added my chargepoint as per the docs now, and it seems to work much better. So meanwhile awaiting a fix, try this:

`chargeamps:
  username: !secret chargeamps_username
  password: !secret chargeamps_password
  api_key: !secret chargeamps_apikey
  chargepoints: [YOUR_CHARGEPOINT_ID]`

**Comment by jschlyter** [comment]
The problem is could appear if the start is not successful, I will try to resolve this in the near future.

**Comment by Bryggan** [comment]
> @Bryggan, I added my chargepoint as per the docs now, and it seems to work much better. So meanwhile awaiting a fix, try this:
> 
> ```
> chargeamps:
>   username: !secret chargeamps_username
>   password: !secret chargeamps_password
>   api_key: !secret chargeamps_apikey
>   chargepoints: [YOUR_CHARGEPOINT_ID]
> ```

I have all that except chargepoint ID, is that the same as serial number or is it that number you can see on the enititys associated with the integration?

**Comment by elden1337** [comment]
If you check the powersensor and its attributes (for example) you will see it as charge point id.

**Comment by HJLundwall** [comment]
I got a key from ChargeAmps starting with "Bearer", but I have no idea how to get the API-key.

**Comment by jschlyter** [comment]
> I got a key from ChargeAmps starting with "Bearer", but I have no idea how to get the API-key.

The key from ChargeAmps (after `Bearer`) is your `api_key`.
