### ISSUE TITLE
No longer reports power and current usage.

### ISSUE THREAD

**Issue by a94marbo** [kirei/hass-chargeamps#27]
I can still turn on and turn off the charger, and change other settings. However the current and longer reported. 
Data is available in the app. I have reinstalled the integration and rebooted the charger and the power meter.

**Comment by jschlyter** [comment]
Yes, this is a known problem - I will update the integration to use APIv4 shortly. Quite bad of Charge Amps to cripple existing APIs IMHO.

**Comment by jschlyter** [comment]
I've just release https://github.com/kirei/hass-chargeamps/releases/tag/v1.6.1 that should address this issue.

**Comment by Farfar** [comment]
Thank you for the update, it works fine now. The Schuko connector is constantly "Unknown" though. Not a big deal but it used to report status correctly.

**Comment by jschlyter** [comment]
@Farfar will check schuko when I have access to hardware (I do not personally own any Charge Amps equipment)
