### ISSUE TITLE
Add support for (un)locking cables

### ISSUE THREAD

**Issue by a94marbo** [kirei/hass-chargeamps#28]
Since the option to lock/unlock the cables is available in the Charge Amps app, I wonder if it would be possible to add this support to the HA integration?
My use case is that I want to lock the cables when I have armed my home security (away mode), and unlock the cables when I am home.

**Comment by jschlyter** [comment]
This is for Aura? For Halo the cable is locked by the car I guess.

**Comment by a94marbo** [comment]
> This is for Aura? For Halo the cable is locked by the car I guess.

Yes, the Aura, sorry.

**Comment by jschlyter** [comment]
Can you test test the cable lock feature in https://github.com/kirei/python-chargeamps/ and report back? Should be possible with something like:

`chargeamps --config config.json get-connector`
`chargeamps --config config.json set-connector  --chargepoint YYY --connector XXX --cable-lock`
`chargeamps --config config.json set-connector  --chargepoint YYY --connector XXX --cable-unlock`

**Comment by a94marbo** [comment]
I am not sure what you want me to do?
I have very little experience in doing changes in the integrations.

**Comment by jschlyter** [comment]
Fixed via https://github.com/kirei/hass-chargeamps/releases/tag/v1.7.0
