### ISSUE TITLE
Entities not created

### ISSUE THREAD

**Issue by vlumikero** [kirei/hass-chargeamps#31]
I’ve now managed to configure the addon to the extent that I can successfully run the services to engage the cable lock f. ex. 

But I can’t find any of the sensor or switch entities. How are they named? What could be the issue if they aren’t created at all?

**Comment by doe81** [comment]
I have a HALO and they are named after the Name_Serial#.
ex: light.name_serial#_downlight

**Comment by doe81** [comment]
> I’ve now managed to configure the addon to the extent that I can successfully run the services to engage the cable lock f. ex.
> 
> But I can’t find any of the sensor or switch entities. How are they named? What could be the issue if they aren’t created at all?

I have a HALO and they are named after the Name_Serial#.
ex: light.name_serial#_downlight

**Comment by jschlyter** [comment]
Can we close this @vlumikero ?

**Comment by vlumikero** [comment]
Yes, we can.

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Jakob Schlyter ***@***.***>
Skickat: Tuesday, January 31, 2023 6:49:52 AM
Till: kirei/hass-chargeamps ***@***.***>
Kopia: vlumikero ***@***.***>; Mention ***@***.***>
Ämne: Re: [kirei/hass-chargeamps] Entities not created (Issue #31)


Can we close this @vlumikero<https://github.com/vlumikero> ?
