### ISSUE TITLE
Error during setup of component chargeamp

### ISSUE THREAD

**Issue by TobiasLainson** [kirei/hass-chargeamps#34]
I'm getting this error after installing chargeamp via HACS, below is the complete log message

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/chargeamps/__init__.py:158
Integration: chargeamps (documentation, issues)
First occurred: 21:16:52 (1 occurrences)
Last logged: 21:16:52

Error during setup of component chargeamps
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/chargeamps/__init__.py", line 119, in async_setup
    handler = ChargeampsHandler(hass, client, charge_point_ids, readonly, scan_interval)
  File "/config/custom_components/chargeamps/__init__.py", line 158, in __init__
    self.default_charge_point_id = charge_point_ids[0]
IndexError: list index out of range

**Comment by jschlyter** [comment]
- Do you have an API key for Charge Amps configured?
- Do you have any chargepoints associated with your account in the MyChargeSpace portal?

**Comment by TobiasLainson** [comment]
Yes to both questions.
I am using ! secret for my credentials in configuration.yaml, maybe thats not supported?

**Comment by jschlyter** [comment]
Using `!secret` works fine. You can also test to use the https://github.com/kirei/python-chargeamps CLI tool to talk the API. The CLI is installed together with Home Assistant so it should be easy to find (exactly how depends on if you are running native, container or HassOS). Example config file in https://github.com/kirei/python-chargeamps/tree/main/examples. One you have that working, you can use something like `chargeamps --config myconfig.json chargepoints` to list all chargepoints.

**Comment by TobiasLainson** [comment]
I'm running this on a home assistant yellow so that should be native right?
Should I copy the script, add my credentials and api_key and then put it where? to be able to run it from cli.

**Comment by jschlyter** [comment]
I understand Yellow is running HassOS. The problem is that the integration does not find any ChargePoints connected to your account. Checking with the CLI would provide some more information. Are you fluent in Python and can set up the CLI on another machine?

**Comment by TobiasLainson** [comment]
I don't know any Python I'm afraid.

Maybe I should have started with the following information about my setup, but I thought this was just a setup bug at first.
I live in an apartment so we have a parking garage with 15 chargers and one of those is dedicated to me, locked to my specific nfc tag and linked to my chargeamp account. Maybe this has something to do with my error?

**Comment by jschlyter** [comment]
The charge point might belong to the building or the installer. I'm not sure if this is supported by the API as of now; there are calls available but I've never had the opportunity to test them. If you reach out to me via email I might be able to do some debugging.
