### ISSUE TITLE
Charge Amps Dawn

### ISSUE THREAD

**Issue by asyvan** [kirei/hass-chargeamps#35]
Can this integration work with Charge Amps Dawn charger, or is it verified to only work with Halo and Aura?
If not working with Dawn, are there any plans to add support for Dawn?
Thank you.

**Comment by jschlyter** [comment]
Did you try with Dawn?

**Comment by asyvan** [comment]
I did not, unfortunately. I am still on my old Easee charger.

**Comment by swebrian** [comment]
I can confirm that the integration works with the Charge Amps Dawn.

**Comment by jschlyter** [comment]
Thanks @swebrian
