### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Timon321** [kirei/hass-chargeamps#39]
I recently setup the Addon and got this error:

Logger: homeassistant.setup
Source: custom_components/chargeamps/__init__.py:158
Integration: chargeamps ([documentation](https://github.com/kirei/hass-chargeamps), [issues](https://github.com/kirei/hass-chargeamps/issues))
First occurred: 14:56:24 (1 occurrences)
Last logged: 14:56:24

```
Error during setup of component chargeamps
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/chargeamps/__init__.py", line 119, in async_setup
    handler = ChargeampsHandler(hass, client, charge_point_ids, readonly, scan_interval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/chargeamps/__init__.py", line 158, in __init__
    self.default_charge_point_id = charge_point_ids[0]
                                   ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by jschlyter** [comment]
It seems you have no charge points available via the API.

**Comment by Timon321** [comment]
Oh yes. That seems to be right. My user has no Wallboxes directly.
But the organisation has the wallboxes. Is there a way to hand over the organisation id in the configuration?

![image](https://github.com/kirei/hass-chargeamps/assets/7792233/31bd6016-af93-4b31-b17f-b9e59da8c2ae)

**Comment by Timon321** [comment]
I have now permanently assigned the wallboxes to my user in the admin portal. Now the integration works.
Very nicely implemented!

Now it would be great, if you could implement limiting the charging power of a charging port.
In the api you can PUT on /api/v4/chargepoints/{chargePointId}/settings:
{
  "maxCurrent": 0
}

NULL seems to be "endless".
