### ISSUE TITLE
Doesn=t work on latest homeassistant

### ISSUE THREAD

**Issue by klotan** [kirei/hass-chargeamps#41]
My homeassistant can=t load the chargeamps integration since last core update 2023.11.0

**Comment by klotan** [comment]
Nevermind

**Comment by rwdnnz** [comment]
Hey - I'm having the same issue @klotan - what did you do to fix this?

**Comment by klotan** [comment]
Just restarted my home assistant. That did the trick for me.

/Tomas



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: rwdnnz ***@***.***>
Datum: 2023-11-04 03:51 (GMT+01:00)
Till: kirei/hass-chargeamps ***@***.***>
Kopia: klotan ***@***.***>, Mention ***@***.***>
Ämne: Re: [kirei/hass-chargeamps] Doesn=t work on latest homeassistant (Issue #41)


Hey - I'm having the same issue @klotan<https://github.com/klotan> - what did you do to fix this?
