### ISSUE TITLE
If OCPP is tured off remote start/stop will not work

### ISSUE THREAD

**Issue by fekberg** [kirei/hass-chargeamps#44]
There is currently a "bug" (still being investigated by Charge Amps) that if the box has OCPP enabled (not CAPI) stopping charging when a charging session is active does not work. It is unclear if this is intentional or not.

A work-around for this is to use the RFID-endpoint instead:

- PUT
[/api/v4/chargepoints/{chargePointId}/connectors/{connectorId}/remotestart](https://eapi.charge.space/swagger/index.html#/ChargePoint/ChargePoint_RemoteStart)

- PUT
[/api/v4/chargepoints/{chargePointId}/connectors/{connectorId}/remotestop](https://eapi.charge.space/swagger/index.html#/ChargePoint/ChargePoint_RemoteStop)

This would require an RFID tag to be created, and associated with the box in the admin UI (or through the API).

It would be a great feature to add to the component to be able to use the RFID remotestart/remotestop functionality.

**Comment by mekholm** [comment]
I think I see the same. Since a while back the charger will not turn off if a car is charging when I get the switch is set to "off".
Unfortunately that means that it's no longer possible to only charge the car when the electricity price is low.

**Comment by ReconOperator** [comment]
Its possible, you just have to change your automation in HA to use:
remote_start -- start a charging sessions when RFID lock is enabled
remote_stop -- stop charging sessions when RFID lock is enabled

And set the charger to use RFID lock. and then add a RFID tag in https://my.charge.space/admin/nfcTags and use the data from that tag when making the action call.

![Capture](https://github.com/user-attachments/assets/93fd0071-ab45-4836-bc63-587394b9e320)


![Capture](https://github.com/user-attachments/assets/2dd99c15-e8bd-4dee-b9cf-a75c5da653f5)

**Comment by ReconOperator** [comment]
By the way @fekberg , isn't this feature request implemented since remote_start and remote_stop exist in the integration?

**Comment by fekberg** [comment]
@ReconOperator It is, I implemented it 😄

**Comment by ReconOperator** [comment]
@fekberg Thanks for the work! Been using it for a couple of weeks now since i got OCPP to my HALO.
