### ISSUE TITLE
After 10 logins from integration the Charge Amps phone app gets kicked out

### ISSUE THREAD

**Issue by MumboJumboMike** [kirei/hass-chargeamps#58]
As this integration seems to login every two hours my Charge Amps phone app gets logged out and I have to enter my credentials every time I use it. Here is the message I got from Charge Amps support: _"The developers have looked at your logouts and it is the case that new login tokens are generated every two hours for your account and since there are currently 10 managed, the oldest are logged out. So it should be that you are logged out after 18 hours. What services do you have running against your charger? Tibber, Greenely, Home Assistant or something else?"_ There is also some talk about a so called "refresh token" that should remedy this problem.

**Comment by jschlyter** [comment]
Support for refresh tokens added

**Comment by MumboJumboMike** [comment]
Thanks for swift fix!
