### ISSUE TITLE
Charge Amp change to OCPP

### ISSUE THREAD

**Issue by gassentb** [kirei/hass-chargeamps#59]
Hello
Will this affect the API in the Home assistantans integration?

Copied from ChageAmp's support

What is OCPP? 
CAPI and OCPP EV chargers share similar functionalities that enable Charge Point Operators to remotely manage and monitor their charging infrastructure. However, they differ in communication protocols, cloud maintenance, updates and technical support. OCPP is the industry-standard international protocol for Electric Vehicle charging. It enables seamless and bidirectional communication between chargers and CMS (Central Management Systems).  Charge Amps adopted the most widely used OCPP version 1.6J to offer the best features and highest security for efficient EV fleet management.

**Comment by fredriklj** [comment]
Yes, it does have an impact. The state machine in the chargepoint is different. For example, you can not disable a port while there is an ongoing charging session. You must first stop the session, and then disable the port. But it was also very unreliable. I was unable to get the API working in a meaningful way after the upgrade to OCPP, for which reason I have now swapped out my charge amps wallboxes for another brand.

This is also why we are looking for new maintainers of this integration.
