### ISSUE TITLE
Too many requests sent to API

### ISSUE THREAD

**Issue by N1S5E** [kirei/hass-chargeamps#62]
Got the following message from Charge Amps:

> We’ve detected a very high usage of our External API by your API key. Please respond back with how you are using our API and for what purpose as we are considering blocking traffic related to your key. 
> We suspect that the implementation is polling based in a way that only adds additional load, without getting any “fresher” data. For event-based applications, the way to go is to use call-backs.

We have 2 pieces of Charge Amps Aura, apparently Home Assistant is sending 4 requests per second and therefore we are now suspended from the API. Is there any possibility to change to fewer requests ?

**Comment by jschlyter** [comment]
You can set `scan_interval`  in the configuration to something higher, the default is 30 seconds. It should not send requests more frequent than that to Charge Amps. It will send one request per chargepoint every `scan_interval`.

**Comment by N1S5E** [comment]
> You can set `scan_interval` in the configuration to something higher, the default is 30 seconds. It should not send requests more frequent than that to Charge Amps. It will send one request per chargepoint every `scan_interval`.

Then it's quite odd, had scan_interval set for 300 seconds and yet it sends 4 requests per second.
Now it's set for 600 seconds and will see if they are willing to unblock me.

**Comment by jschlyter** [comment]
If you turn on debugging in the component you should see all updates.

**Comment by jschlyter** [comment]
Did you find out what happened?

**Comment by N1S5E** [comment]
We were blocked but now it works again, seems like the requests sent to the API has been fewer.
